#Write a program to input eight numbers from the user and display all the unique numbers(Once)

s = set()
n = input("Enter Number:")
s.add(int(n))
n = input("Enter Number:")
s.add(int(n))
n = input("Enter Number:")
s.add(int(n))
n = input("Enter Number:")
s.add(int(n))
n = input("Enter Number:")
s.add(int(n))
n = input("Enter Number:")
s.add(int(n))
n = input("Enter Number:")
s.add(int(n))

print(s)